module.exports = {
    CATALOG :  `
    query ShopifyProductListQuery($pagination: PaginationInput) {
        ShopifyProducts(listing: { pagination: $pagination}) {
        totalRecords
        pagination
        pagesCount
        data{
            name
            description
            reference
            descriptionShort
            active
            price
            manufacturer
            tax{
                name
                rate
            }
            mainCategory {
                id
                name
                description
                parent
                active
                url
                level
                createdAt
                updateAt
                dafiti
                mercadolibre
                linio
            }
            categories{
                id
                name
                description
                product_id
                parent
                active
                url
                level
                createdAt
                updateAt
                dafiti
                mercadolibre
                linio
            }
            gender
            mainColor
            width
            weight
            height
            length
            images{
                file
                position
                cover
                src
            }
                variations{
                    quantity
                    reference
                    talla
                    gender
                    upc
                    price
                    ean13
                }
            }
        }
        }
`
}